### ISSUE TITLE
Using of Fiber instead of Gin

### ISSUE THREAD

**Issue by yuvicc** [SANTHOSH17-DOT/are-you-bombed#10]
### Is your proposal related to a problem?
We're using gin as http webframework which has very low performance. We can see [here](https://www.techempower.com/benchmarks/#section=data-r21&test=composite).
Also the documentation of gin has very bad interface, new contributors will face difficulties in getting started with this project.

### Describe the solution you'd like
I'ld like to suggest the use of [Fiber](https://gofiber.io/) which is very fast and has very low latency. The fiber can be easily understood by the new developers, also it has nice documentation. The composite benchmarks of fiber is far above than the gin framework.

**Comment by SANTHOSH17-DOT** [comment]
Thank you for introducing me to this benchmarking tool. 
I can assign you if you want to update the existing code with the Fiber web framework.

**Comment by yuvicc** [comment]
Yes, please assign me!

**Comment by SANTHOSH17-DOT** [comment]
Go ahead @i-am-yuvi
