### ISSUE TITLE
Upgrade the README File

### ISSUE THREAD

**Issue by Suryansh1720001** [SANTHOSH17-DOT/are-you-bombed#20]
Hello @SANTHOSH17-DOT 

*Is your feature request related to a problem? Please describe.*
### Features that I want to add in README File

- Contributors details
- Project admin details
- Add the contributing line with a guideline link so that everyone motivates by that.
- Center heading for more attractive
- adding the footer part in readme file

*Describe the solution you'd like*

- Add new features

**Kindly assign this issue to me under IWOC event with the label of MEDIUM level.**
please assign asap

**Comment by SANTHOSH17-DOT** [comment]
Thank you for showing your interest. But I feel the contributors and admin description in the readme to be redundant since we have a separate section for it in the repo and readme looks fine already.
@Suryansh1720001 
See if you can contribute anything other than **readme upgrade**
