### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by SANTHOSH17-DOT** [SANTHOSH17-DOT/are-you-bombed#4]

**Comment by Jatan88** [comment]
Hello there, I would like to contribute to this issue.

**Comment by SANTHOSH17-DOT** [comment]
@Jatan88 You may go ahead !!!

**Comment by Jatan88** [comment]
Hello Santhosh, the links provided to download zip bomb files are not working.

**Comment by SANTHOSH17-DOT** [comment]
@Jatan88 Make sure you run the server locally

**Comment by Jatan88** [comment]
I tried to run the server locally using the commands provided in the readme. But still the links are not working.

**Comment by SANTHOSH17-DOT** [comment]
Have you set the port in the env file?
Set PORT=8080

**Comment by Jatan88** [comment]
Thanks, now the links are working!

**Comment by Jatan88** [comment]
Hello @SANTHOSH17-DOT , I have made the required changes, please have a look at my pull request.
