### ISSUE TITLE
Dockerize the project

### ISSUE THREAD

**Issue by SANTHOSH17-DOT** [SANTHOSH17-DOT/are-you-bombed#8]
- Generate zip bombs
- Run the server

**Comment by yuvicc** [comment]
I'll try this!

**Comment by Anuragwagh** [comment]
is the issue is solved?

**Comment by SANTHOSH17-DOT** [comment]
@Anuragwagh Yeah, it's done. Any other improvements are welcome

**Comment by SANTHOSH17-DOT** [comment]
@Anuragwagh Yeah, it's done. Any other improvements are welcome
